name: PlayerCompassPlugin
version: ${project.version}
main: net.kunmc.lab.playercompassplugin.PlayerCompassPlugin
api-version: 1.16
commands:
  playercompass:
    usage: /playercompass <player>
    permission: playercompass.playercompass
  playerposition:
    usage: /playerposition <player>
    permission: playercompass.playerposition
  playerpositionoff:
    usage: /playerpositionoff
    permission: playercompass.playerposition
  changeupdateperiod:
    usage: /changeupdateperiod <period>
    permission: playercompass.changeupdateperiod
  kun:
    usage: /kun
    permission: playercompass.kun
  kunxyz:
    usage: /kunxyz
    permission: playercompass.kunxyz

permissions:
  playercompass.playercompass:
    default: op
  playercompass.playerposition:
    default: op
  playercompass.changeupdateperiod:
    default: op
  playercompass.kun:
    default: op
  playercompass.kunxyz:
    default: op