name: PlayerCompassPlugin
version: ${project.version}
main: net.kunmc.lab.playercompassplugin.PlayerCompassPlugin
api-version: 1.16
commands:
  compass:
    usage: /compass <player>
    permission: playercompass.compass
  playerpos:
    usage: /playerpos <player>
    permission: playercompass.playerpos
  playerposoff:
    usage: /playerposoff
    permission: playercompass.playerpos
  changeupdateperiod:
    usage: /changeupdateperiod <period>
    permission: playercompass.changeupdateperiod
  kun:
    usage: /kun
    permission: playercompass.kun
  kunxyz:
    usage: /kunxyz
    permission: playercompass.kunxyz

permissions:
  playercompass.compass:
    default: op
  playercompass.playerpos:
    default: op
  playercompass.changeupdateperiod:
    default: op
  playercompass.kun:
    default: op
  playercompass.kunxyz:
    default: op