name: PlayerCompassPlugin
version: ${project.version}
main: net.kunmc.lab.playercompassplugin.PlayerCompassPlugin
api-version: 1.16
commands:
  playercompass:
    usage: /playercompass <player>
    permission: playercompass.playercompass
  playerposition:
    usage: /playerposition <player>
    permission: playercompass.playerposition
  changeupdateperiod:
    usage: /changeupdateperiod <period>
    permission: playercompass.changeupdateperiod

permissions:
  playercompass.playercompass:
    default: op
  playercompass.playerposition:
    default: op
  playercompass.changeupdateperiod:
    default: op